### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by weihanglo** [mitsuhiko/unbox#1]
Note that the performance is 50% slower than system tools. How can we improve it? Are the compression algorithms the bottleneck?
I am willing to contribute but need someone sheds light on. Thanks.

**Comment by mitsuhiko** [comment]
@weihanglo depends on the format. But yes I saw some obvious improvements here. For instance for the tarball unpacking a low hanging fruit is the `unpack_in` method of the `tar` crate.

Absolutely would love to get PRs both here and upstream improvements to the crates this uses.
